### ISSUE TITLE
Error message when trying to push assignment

### ISSUE THREAD

**Issue by cdapper** [UW-POLS503/Assignment_01#13]
I just attempted to push my assignment up to github and got this error message:

remote: Permission to UW-POLS503/Assignment_01.git denied to cdapper.
fatal: unable to access 'https://github.com/UW-POLS503/Assignment_01.git/': The requested URL returned error: 403

Before I committed, R warned me that the file was really big and might cause R to "hang" or take a long time... But the commit seemed to work, I just can't push it up to github now.

Let me know what I should do!

@jrnold @CasAndreu

**Comment by CasAndreu** [comment]
You are getting this error message because you cloned directly the `Assingment_01` repository in `UW-POLS503`. Now you're trying to push into that same repository but only Jeff and I can push to the assignments repos in `UW-POLS503`.

When starting a homework assignment, each student needs to fork the main assignment repository and create a copy in their own GitHub account. Then you need to clone you own copy of the assignment, work on it, and then push the solutions back to your own copy and submit the assignment by making a pull request. See detailed instructions in [here](http://uw-pols503.github.io/pols_503_sp16/submitting-assign.html#1_fork_the_repository). 

What you can do now is:
1. Fork the original `UW-POLS503/Assignment_01`. This means you'll create your own copy in your GitHub account: `cdapper/Assignment-01`.
2. Clone your copy of the repository in your local machine using R-Studio: `File > New Project > Version Control > Git`. 
3. Copy and Paste your `solutions.Rmd` file to this new repository.
4. Open the new `solutions.Rmd` file and make some tiny change.
5. Commit and Push the changes to your online version of  the repository: `cdapper/Assignment_01`.
6. Create a Pull Request to merge your fork to the main repository. You're done!

If you or others still have issues, try to stop by my office before class or we can also deal with them in the beginning of class. 

cc @UW-POLS503/spring-2016-students
